[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "c050251aeb9cd5a79df20d4fa0ac0bdeee6a357a"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "b6b9892baf25e3086509443de2b1e5845d53ca2c7ea7c06c72c8f1fa01062f28"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.aarch64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "951a9164ec977fc403c10ac2996e2fb49fa9f64d"
os = "windows"

    [[NetCDF.download]]
    sha256 = "d094f27cbfb6e4615892de029928b01b348b55c325429876fb74f0cb07fda8e7"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.i686-w64-mingw32.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "60349e753de4ff9069c6f0fa1d3d079948794a5a"
os = "macos"

    [[NetCDF.download]]
    sha256 = "b3ceba94327f33bb22ae42d2ee348de20ac321e1cffcdb842f13053e91e4f337"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.x86_64-apple-darwin.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "877149aedda703fde4a848bffd955df8934ca876"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "0eb005945041c66a020aa7dd802a82a327095f43be9791d46bd741a28d843fed"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.x86_64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "39751282bdcf93bf733ec950163c056a83c91bbf"
os = "windows"

    [[NetCDF.download]]
    sha256 = "c49320c4d796c5fa746affa52b4713d1b314b3a79db18249cd4dcbb035899abc"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.x86_64-w64-mingw32.tar.gz"
