[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "8afd74fe32d9450720855edd35a21335b21c3543"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "e75fa31701164bdbaef4543ee0ad549cf99b256d49a728f76fb702d2dd6fe7de"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.aarch64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "a028e486318af151fa6f5947df46cefd70aaec3f"
os = "windows"

    [[NetCDF.download]]
    sha256 = "f3e2696b7a58f234a4e4e62812cdf35a33b523948a065fc5734d81f9140a89b5"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.i686-w64-mingw32.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "0b76e1dfbb6f2cdf5803502495ca4edb7cd14a77"
os = "macos"

    [[NetCDF.download]]
    sha256 = "39ed3f3546fc54d48bf3453eeded8580785d423d55d26860c4ba9f63e467f800"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.x86_64-apple-darwin.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "32592bd7ed164c9c73506ebabfa0812690024de5"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "622e549296d3c50c6d1dce2c41e866c21e3da8c828c83b6953485f9fa0ee8784"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.x86_64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "837657f8c14ad42cf6c7a3251c254913797f4364"
os = "windows"

    [[NetCDF.download]]
    sha256 = "7964e4077395006d57567a90251dec98c7f7b3edced88d57430173fc3cb772c0"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v4.7.4+1/NetCDF.v4.7.4.x86_64-w64-mingw32.tar.gz"
