[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "8b2c8bc12a13efbc55a3e6c0334604e4c367931d"
lazy = true
mpi = "mpich"
os = "macos"

    [[NetCDF.download]]
    sha256 = "609e9b87de93b779e4751b3bce5f893358bc9cee915c936aaa2025e6fb756c3d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "2b758eace01715ce0b0ae17b72ecb1fcaead2c74"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[NetCDF.download]]
    sha256 = "18fa9b0ccec032d3c459b65e1b7702e2036778035a5e84101bccdbe2c11dac1d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "63a36507b63a92aaf69cfc12c39e4a022b415194"
lazy = true
mpi = "openmpi"
os = "macos"

    [[NetCDF.download]]
    sha256 = "fe097bab4d80d8969a4dd15c07646582e8bbb0a16a05ac458f922a8aa4934a56"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "238299e449e35b8ec000a76d668595d7a87f2f9d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "74a60555638f88e4b11ca4cf98d7b59baca90d8513741c43df4db03705a7776d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "eaf843f5d18de5e556471c48eb59ab5fb8fb93a3"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "d78c20fa7521f21628e8244d0db54f0881fa436e9a11620ad7d06c9ecdc7eb96"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "c589cf09b08c00e1e40186a8dbe6c7a50ed14645"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "80e30120c8cd02cfae4a041a0409371b613a38f5d57b78817d91a2c2a5c7ea66"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "56e28de674849f1e2361068b844170bf7f333a6e"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "cfe21990ad8643b192af8dcb34db322abf45888e3e4f8b61eeaf0031bd0d737f"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "0af056ccffdc281efc211e3357cfc517c25729c5"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "89d77a3cc8e430e1d9e4022d4bcd217b3dc88c00483b9550da5b5ad87b778a9f"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "5b44cb941c326d08832623464b26484d597b0e62"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "9fa34e998ba1b050abf9b101b8130c749943a77ea7715f6dbbbc1bb80bdbaa1b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "8426c0c5e9edbda970f4d46f1c9564b514495e01"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "6e14eab684eb5acb4cb429207b1d5034a7a99fa07a55d762d95872609e738a55"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "e879e759829ee5857b45481271db6ea38db51e6c"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "68127d6b6944b28c3548ac907d81a73fbcd0fa7458faa034de72c376b8d560d1"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6f6bfd80fd5f7114e9ad81ab5f074eb5569a979"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "9c1be76f0b0006aaae75ef6dc5c11d3b82fd64a4dbfb9939685a035c9b9c9174"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d0ff697ad89216aa9631e3c8b4ad6869f9cbbd56"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "43c4083f2261eaccb37824bb0fa4569669c65c63fb8836985f44d8b92dff428e"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f283a85d22e3cedc855656bd8c1fc7135b2b02f5"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "abb1190ccff59e636bf90e0ce53101dbdd42ce8dcc919ae786761e3e23a22521"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eaf74ddcf5ed9fc46f01121f761bfd946ebd1380"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "4bbd08a7596d0ed005df6bb410e20eaf940b7f75988f682b89d1effadfd0a415"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv6l-linux-musleabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8f1b6e4dff970202edb7a12cd730cf6a2f0e4bf0"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "a3b915d7424f110a4f18180481471d38e60debc376c0f3a70b03bb5492887965"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8e5bb6601291b965c0af6a95aeeb6e18b2ff46a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "354b0486d9495b8b521841ff359703e6ae6154a890d7156740ce3dfd1cff090a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab551ccef5651668f4cade4eb82da9bb22d8c152"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "1e196200ea5db3e6f74f0043e904bca0f43a7035372f9c3a6e5a5bf31bddd2c4"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv7l-linux-gnueabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9fe99e56e71aa091a196487af90502600e6dc819"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "3528cb01d571f0ec3b7cd877dd3489a14e253b43e7075101482208dd3f4628c1"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b7929d36d58b7e6d220d27f9b31912cf0de9b84"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "7cfd18285d444edf6020d5a271beb8391689c62664a54fca70f388d916d89f70"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.armv7l-linux-musleabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "cd1c70023775f4637129567094b1514a5557bcdb"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "d82090f78912ec7a00195c664fd46a1ffe71e796f9a11e064ca426b2d807601e"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.i686-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "bb61631e9ce20f91b911a45d51db6a949261d41b"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "86544857598d525cef21234f77b1943e93856e486326310605882fda0e5acb07"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "95f13ad83b22eb4adee3fbdc19d57d366932551e"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "f2c9116ff9478d21b1bcb8a46a8e0499cdf8409aca4456ac816192b6b6187afa"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.i686-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "ab3aa753dbd71456ead8d9c515b44541e051f746"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "50734ecd81ea680f37779eb71d28f770454457956f02b3220b8decf793b82045"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.i686-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "adaf004a4e749dda3b4ba5aa7edd6f2675c85be6"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "eaec9b51b8fb86f5a17bd0710c7ecd5a7475c3fdd22274f31ecce59a5fb1677b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.i686-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "7ceb97367d649b4c616f77b287f21c4c383c653b"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[NetCDF.download]]
    sha256 = "5c94a5dcfcf3daf4308a0502b6a39bbe6b1deec1b9e245015b156ca3c3daa9b5"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.i686-w64-mingw32-mpi+microsoftmpi.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "c19e4a40040be998a0a239a36c8db26c416bec20"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "7ed6bfef96377379a835bd25edc7d280b2557eff6a770c1f196e08b782c95bf6"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "7c05860c444457b65251c70ef31b528a42cb741d"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "7635ba91ee270946d940fa5caa2cb15ccbf5ab1aa9ace0d85ed58f45830350db"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "07b3a4f96c743917ef2264131958a6d17a08fc50"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "e6d11b22326ebada8c697e2cde0eaa1655a45c7682ff06cacd1df063939be7b7"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "riscv64"
git-tree-sha1 = "ff7e70b3a31e00eb33f4e5b1be4628abbe131cdf"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "15961383fd0e233beb4ebd99b567c9d7187cb7cf57fd6d987ecbff3f28e96a38"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.riscv64-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "riscv64"
git-tree-sha1 = "30d49b657df71927178f5f381faeab867abc058f"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "b4238b46e9cc2dc0f9646b30ab8dc6ffa0f0116ca285c0434c744421c5fc2c25"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.riscv64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "riscv64"
git-tree-sha1 = "b295e393ccb0f402bab30d2073c569aaf832c0d7"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "baaed7f4bc6a8ee9bd233bc6c3b3b82dd3b9533a1cd0abbcbbc4c6024bf6514c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.riscv64-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "a65333512de52a07a3c9cc2047b02945a29df3a8"
lazy = true
mpi = "mpich"
os = "macos"

    [[NetCDF.download]]
    sha256 = "a0ec0c8b2458e9a4da86a85dbb413ae18401d9fa5fc79a451e05455a7533def0"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "997df53222b9fbeef09a0bc83674ed4de896a4f6"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[NetCDF.download]]
    sha256 = "862d86eb5ba93ccc889b8eb0be6cb970483b0464e8a8b661b0dd6f8f29a235c8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "dad53868f7193862e3ec2d89818feb59f878bfe4"
lazy = true
mpi = "openmpi"
os = "macos"

    [[NetCDF.download]]
    sha256 = "8235564a93c4d8bded74ddfea7a9eb1ab1d06f8dbaedde4745076c505ab3eace"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "2dbbcf6f14a16f5b58c7aff3de7a9aa8d2134300"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "557d90fa91cbf80ffe5b52061345d85fe9c674d2f0957d08a7e3e3af0f3dccc2"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "fe74c5e3593f8169484884c06d91da140792084f"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "39f94e0241b53d7bea83f4bf098ae7597263ea616a1ae645a0824a7e3027ebb0"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "58384c300bfef99c751bc88fbe8c2ef718eaec5f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "63879fb51fa4a8984eeeee61ecf44c8ba7f36b148fc3c59e64bd6ba76feb58b7"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "56244009c941611a2f5bbdf590967d66213e8fe5"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "5760196792c282b37b841d464d663febee2648c7620491f32884a5fa6912afc7"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "49bfdce1b06640e659a3be41cecaa4ce46dc3cb9"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "e894634f2e4aec2072f99c61b87daec1af28cb9dcc29b5397921bf8d7d162eb9"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "88895ecc8bca26dd441123af8a9ee139537ca8c2"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "8a27360061860264e33d88a35bf1fc26d3e1034da49126852db8c324211f743b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "fd036099befe0ef0ce23121665fab728ad0d9900"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "3d655d62643f905463c649ff02711a37cc3eceb0a43d81fe6a6a05b77f133978"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "4932379760c263161349e7bec9b83579a74a3112"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "c86d070cb5c1e9928486fa3d0703b3cd4b96bc279a98b9523394eac1bf66fcb4"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "bade52dee31407c455f119c194ded80196069aab"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[NetCDF.download]]
    sha256 = "ab0e39407b56709e1f474443cd61440e3eb370eed2b2cf2e8706f3f692fd2538"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+0/NetCDF.v401.900.300.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
