[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "a140d924bc47ae6c7cde3f380e5f3983114cc5f9"
lazy = true
mpi = "mpich"
os = "macos"

    [[NetCDF.download]]
    sha256 = "c6d36311d1a605dc6b2016306a88722414415de8528a1a435c4c08af792962cf"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "03abe81f225e0ca34d59b8d760db5f436575bb3a"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[NetCDF.download]]
    sha256 = "84490f83c5e827e99140c82509ca43d18c6c03151b03c87f943d75d6878a6259"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "4060b9bdcb12d541543a8c2d2d545e665b7ed083"
lazy = true
mpi = "openmpi"
os = "macos"

    [[NetCDF.download]]
    sha256 = "3039299ea29536bcb096efc213d047729a10edb5004b56b2f405263501cb7c61"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "21082cfa49f53aafd4d88edcf5afcb8f39464b1c"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "f46439f323347abd9d62c826335a22a7e2915f9b0adad68d37f6738aea6cc085"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "697694386718268a23b97269d7d07611e088f5c9"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "5476100bc04712fcca3ed529f34f09b2a192f23c0207019423e18201a231dabb"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "b0eb274e187b1bb483abfc9d7d6b5d567e2c6a5d"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "1190b30426fd5e952c836c1e6e4be2ce4ebb6b3c2731dcb4d90d9a42d3f17a58"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "5ea656baaa9b9b679213768adf544c50a7e8384a"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "de81769ff535cdcdb838608dd4c0a5ce2614579e0e3c208b561b4e29a26407f5"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.aarch64-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "7936c10608d2656eb1fd1de1183892e1061c85ad"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "0bdfdb88537e2d586ca214d5460be2c1a200adf9755dff209e67e8f460a65566"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f891e087e386b911fcd257ae7154a5c50a4c70cd"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "4d50e752b21e4ed98e4dffe87e943b73f9afa98d5bbba1b568685e3a64b1b64b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "548ecec3eb23f1990a28ab0192d8bbeb7ab5ac2a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "1e1529b689d30f617e8069800ec2f6bd61c263b10a77095d129a52ad21303e0f"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f31fe1dc9fc3c871e47a9e74dd2bba4ef6118fa2"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "f271ecac51f8b96edf5944df94be4cd1fd331db80e89847f87ea32a588cade66"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3bc086ad5d5f694eeeaeefca260d3d9169ac35a5"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "e8bd3a89b836357238aef08bcc335e2b8d53abd7d4a7296f2cc74e3b825bee18"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv6l-linux-musleabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d5b96b2a92d1f7084e6ab608f05dd518297cbb0"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "0251ad42227705b68e021822ee576fb68f8327dc9bf005f4bcd17295598581f9"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "65914e235ccd0f953fce31c6ade1ed38f236880d"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "03f5ae276f2c19ba1985d0fb3a57760c206f84effd615bafbd804df106f9ccd1"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "84341a579092849a6e6e5a750078e49aa6b204c5"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "3790faf2a0efa75693cddcd7f2a42526377778d1769022167e347c6330aac467"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv7l-linux-gnueabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "93b952869ebadda03cd6a18bc63e2d5c03de2dfc"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "04cb5eb48c2c93078f085e6fdd08cdf147273591eb1f79561fa3fa3c632b4878"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "451f0a227d6d8b945a64ec152f0cbf9ee9663d53"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "617a5e20397b0b7086ed9eb755fabd0776848ea09e283802e9de3cde956c636f"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.armv7l-linux-musleabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "30a83cb623d9a0cea603a192f21428e07373e0c0"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "23e64b97d8b18e748c89488343e5ddc901eb142aba0f1bcc7004e6d7d10f050d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.i686-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "61399df357a7a4f6da5f81d82a7ad88ecfb60cab"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "fa06922fbf79774ef4f0e783d33b5a7f7e3008ffca78fa6f5716d108debc3056"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "8d533dd92d4852d6d220f07f9f95d52d060480a4"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "77104917c51a4d5d5396f11713514abfc82f811a6518144d38eb9eba166eb277"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.i686-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "8609c7395ba3d24a92259b0b7b5821ca11de2223"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "13000d4f1cb6da39295906ca437ee7f5c1411a6de0c9a1608468be4af07bf261"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.i686-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "ad33963585cd30a2b747deebe807eb25b8ace6c6"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "78151ad199c61ec80ed538a470e0ef32f532d8bc7c238546ba8049f3370d44e4"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.i686-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "71a1055bb22527bb9930286018f5a6254e39c235"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[NetCDF.download]]
    sha256 = "25644aa9361eb4f36923217f02f697983a3cc5860041e9257ea526c91be4db21"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.i686-w64-mingw32-mpi+microsoftmpi.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "51e1e2ed6f6dbe77447431d66fc8b715d7338c3e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "7439a81e84a9f1290905168f5108826432a9eb86989645adc8a2aa919b9995d1"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "f4a17562556f1c215f35a6a7616056a7975e99ca"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "219a84461daae6afabc3b2da3edff96e19763ca23e7b560f3b9973e5ad764934"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "2fd09562e6968519014023df1499cea042ec6bd4"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "2c50230dbe954c9ab93f3082ed9bbb9cb7193c2f5beb373ca52e2ef3d8086e54"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "889b1848bd4fc47b6839e0d178bdd635eea9091b"
lazy = true
mpi = "mpich"
os = "macos"

    [[NetCDF.download]]
    sha256 = "cc17ccc14b488232dd258918745e646ddff3430353d0c35802f19676946000c0"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "4675e8f2d06ddd665e0c64b61124818c801cec00"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[NetCDF.download]]
    sha256 = "0f6dc288d29b4aee6c50711f14c294cc08d13a712be168ee55cbcbae0dfa35cb"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "87987a101394e20e90d1432d3a403ab1687f60cc"
lazy = true
mpi = "openmpi"
os = "macos"

    [[NetCDF.download]]
    sha256 = "069a0d87cd455652d4f751c79ebc3e41b88b9463801fe8a08993403d827a0f5e"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "e427f8c9b0b4143075f66cdddeb45f13420d5975"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "a25b9696d0b977afd5074c9d7d5e3ca5df43fcbc22347180695454525cb70b14"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "f298d22a4d79de3576122b66c26a3ac330fc5f3f"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "3dfe895fc07bd07acedbc83dc3d3883ab55bb0224aabffceb9e61b6b240126e8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "b3fd386e35376fae83f9bfe93006fa8ec2ace42d"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "a634bf700a7727e0de7fce1aa2b13a3b368f85bf371f5d941e85ef4fe1bf7f40"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "0ebb98e135bac9ffed2884f849fdbcc80af168b2"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "62a1a65b3db4063b6760cb63e2f2a8176a27f1ea75918c2dcf9d345d898c51ab"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "31fa3d398b4a42f36fa3ace99f2a7d111c16f95b"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "4bcd8704f266596921d44adf6b3272ac69a9d236ff0d2ebdc3a643c539bb903f"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "7b53688ac0a942ca7f5e7689ad51526cf8f38b80"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "419b71614dd6e68845869c3b53bc61c2ff054e8814fca54ab57f7010f1d01f1c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "7e46654f56acfeebdba771da7bae91809e63dcb2"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "bed3185029ce44d9623142000a3fc82cd265b3856302a3dd56ba6356feab9957"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "a0f65aec92810567654b7ca3b29b0786088806a6"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[NetCDF.download]]
    sha256 = "babafc405b44e0d2b670e4b25c228969e4347c64e8d2629a44f132a87c6432dd"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.211+1/NetCDF.v400.902.211.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
