[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "413341c1b4621c5e7a3d9e3f0dd69b1ba722d7c3"
os = "macos"

    [[NetCDF.download]]
    sha256 = "94cfc32124cb5f52d5e313ccd5e04502bc2bd9197caa928058dba829be41114f"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.802.103+0/NetCDF.v400.802.103.aarch64-apple-darwin.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "dfdc60dbeda907cfc63b853be5c7daa8df7e313a"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "abf893b98ce0b8f8443ba2e8e637c5d5416cbbcaaf08add788aedb8ca8174ebf"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.802.103+0/NetCDF.v400.802.103.aarch64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "a56a3e0e95d9279e382c35ea839e8c24ab8cdc07"
os = "macos"

    [[NetCDF.download]]
    sha256 = "d2768dd2bb5b0e66f0189de5db9cf59c49920abfe0326ee2191c43af19d76e09"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.802.103+0/NetCDF.v400.802.103.x86_64-apple-darwin.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "d8d4b55b5f7b6852350fb25254d7d9a65e651698"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "893be5189666802245d5fe044d9e7722212ec55c2a222ee0c9abfd3fed6f8e23"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.802.103+0/NetCDF.v400.802.103.x86_64-linux-gnu.tar.gz"
