[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "8b2c8bc12a13efbc55a3e6c0334604e4c367931d"
lazy = true
mpi = "mpich"
os = "macos"

    [[NetCDF.download]]
    sha256 = "609e9b87de93b779e4751b3bce5f893358bc9cee915c936aaa2025e6fb756c3d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "2b758eace01715ce0b0ae17b72ecb1fcaead2c74"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[NetCDF.download]]
    sha256 = "18fa9b0ccec032d3c459b65e1b7702e2036778035a5e84101bccdbe2c11dac1d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "63a36507b63a92aaf69cfc12c39e4a022b415194"
lazy = true
mpi = "openmpi"
os = "macos"

    [[NetCDF.download]]
    sha256 = "fe097bab4d80d8969a4dd15c07646582e8bbb0a16a05ac458f922a8aa4934a56"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "265e0e5f9c97a5c6b589152465cbc6700b1cc797"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "a2bce1014c1d19a3342338e5b9fb0bd5624617c648a6e74dab3f79fea4a51baf"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "342fa7ed22cf3ec356f13f166e3c46b1695e4692"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "2d3832134930f868cf7517d5b7a0f6aa20035367c365c5857b96e5833df1b1a7"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "3853ca2efd7d7ea5b033eac03e7bae7feca18bdb"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "1f2ab61ecb2ef203667d93ff07a823e25ba85bd9bb7fee0ad0f22b3e74078cee"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "10e6b2c538ddfaf963e6b90554bf20ea09663104"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "e9104ba8d1c9a63933c1e1538cd552aa9f94ee77b865ea35f4214cecaa6d372c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "c39246bac5445e06c5b7dcf377a0df5f7d023de1"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "9f45cb38887dd9bbedf0c9f5197729ab9931b0aac312b93274ece2cb366a32dc"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "5b44cb941c326d08832623464b26484d597b0e62"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "9fa34e998ba1b050abf9b101b8130c749943a77ea7715f6dbbbc1bb80bdbaa1b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "8426c0c5e9edbda970f4d46f1c9564b514495e01"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "6e14eab684eb5acb4cb429207b1d5034a7a99fa07a55d762d95872609e738a55"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "e879e759829ee5857b45481271db6ea38db51e6c"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "68127d6b6944b28c3548ac907d81a73fbcd0fa7458faa034de72c376b8d560d1"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1fe4f4367ad4eecb74d62743fda664a1b6650f44"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "1dde3aca2ea75bcbfd12959ec3e1ff8a4340dddd73d36420f102207cf4e8356b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e55dbaf9c9928a09ed0e74aeff2f239b1918787c"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "440eba041b23586074254936fd71961db9b1dd913308fd034b6e81515c287602"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3b63bec92adda83e937426e451c0b56c52194692"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "96e7cf5e86684d491de642e4fb97081ecdcc379fc56dc190cf0d4718f9be62f2"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d99c0bd3a1c790eeb60402e3590d816fbc49539b"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "1582f480c6fb080e327b02060e067a0778bfd562c50f3c74b45ef518ea05c302"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv6l-linux-musleabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b7edca6a59963c09838c77d049369cdfe6ef341"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "6a26d2adcd56d1b258321828a8ae38ccef35bee4230acb0389ef09b6790d851d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f2df44a822792c081c66aa79e9fb39b5178bdef"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "b52fff4f3e11c50b8d70504beed6ba4be96bed0a31b987f1daa9a32e21157be1"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "100f0eb5c34517d59d6181e5dab401e987def1c1"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "e43685886cb00305462bb44272898a23f4f53cd4b61c8a4ef4dcfefc6fd437db"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv7l-linux-gnueabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8fcc864d11f8e974334d7cd198d69e829e3249a7"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "cd44274c817c480e6ddf430d1e4323a75678f944e12af23d3b3a25cc327ff317"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a442cb0d937401d910779ba7fe749c354305ef3"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "19d06713b7084ff65836f85c76ef231e53b060d9ac039198cf2034d60c861830"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.armv7l-linux-musleabihf-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "c2dcc8cab78571c05dd51cee285f763b2a28368f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "31d451d571bb1b0c18dd4d47701281e24d3c33818e59a5dc83b18940cc7f498a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.i686-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "d686ea23b3c176a73bce15df1c11adab4fa91793"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "ba65c77d9e984acea339aaa49b363472b4d8b345eee656ef1c4fba1b0ef0e252"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "5a771f06a9fb3788f1035974a426468c8e72d42c"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "a657f72873c187c251b1bee6c49ff3ae2caaeb468b09e5c904a42ea9e3a4aef4"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.i686-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "31a04577256143c24dc561ddd9b90b0b434fe2a7"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "050aad83b05a82721320991ed8c812a6694bc6fa57689be6b8fb69048e1c428a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.i686-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "4900097d4ff397131d30e2967242a14cc8dc24ae"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "7e61753d3fd0beac2e890374b5566966d81aabba9c9e4b3cdb8e6d25990b7ca5"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.i686-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "f20f772fd1943b4098d540c118384bee5798be77"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[NetCDF.download]]
    sha256 = "f6efb44f552404890d20244571e2f585cc5bcf3c5bdf7ef36d54ae05cb6afcd5"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.i686-w64-mingw32-mpi+microsoftmpi.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "45cf0870640da636304f261719d842cddff3240d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "323a532cb195450cf8a8e6f1352175094502dcb48c7874c37df56c16597af54a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "e47c0ff15edb0ebd533c9b12483cd57bedac75ae"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "cc9b131b56d33d14417ad79d9e63589d57d70b84418e6505fa2c00fce16184bd"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "8ee434eaed9bc90b9335e0ab45295462cf780fbb"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "526b88e18d9d637dc86bd487eb49d0589a0faf7d5dd1acce36d6f97a46dfd4df"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "riscv64"
git-tree-sha1 = "ff7e70b3a31e00eb33f4e5b1be4628abbe131cdf"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "15961383fd0e233beb4ebd99b567c9d7187cb7cf57fd6d987ecbff3f28e96a38"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.riscv64-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "riscv64"
git-tree-sha1 = "30d49b657df71927178f5f381faeab867abc058f"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "b4238b46e9cc2dc0f9646b30ab8dc6ffa0f0116ca285c0434c744421c5fc2c25"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.riscv64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "riscv64"
git-tree-sha1 = "b295e393ccb0f402bab30d2073c569aaf832c0d7"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "baaed7f4bc6a8ee9bd233bc6c3b3b82dd3b9533a1cd0abbcbbc4c6024bf6514c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.riscv64-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "a65333512de52a07a3c9cc2047b02945a29df3a8"
lazy = true
mpi = "mpich"
os = "macos"

    [[NetCDF.download]]
    sha256 = "a0ec0c8b2458e9a4da86a85dbb413ae18401d9fa5fc79a451e05455a7533def0"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "997df53222b9fbeef09a0bc83674ed4de896a4f6"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[NetCDF.download]]
    sha256 = "862d86eb5ba93ccc889b8eb0be6cb970483b0464e8a8b661b0dd6f8f29a235c8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "dad53868f7193862e3ec2d89818feb59f878bfe4"
lazy = true
mpi = "openmpi"
os = "macos"

    [[NetCDF.download]]
    sha256 = "8235564a93c4d8bded74ddfea7a9eb1ab1d06f8dbaedde4745076c505ab3eace"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "0bf814932266f07808c995f4e02d84c3e29c4876"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "9101b996a48c07798b2931f774c38c3dbeafe7d34de40f2064a97b7d8fcc42f3"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "b37d3be8b72121a93389bba694d8303cb3eba186"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[NetCDF.download]]
    sha256 = "b0a9d6bfb6b146579116c5cefec47e536e663cffb6741ada3e0541978b6a88a0"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "dd821d66b3aa5bed7f7172fc20c5004843aead9c"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "20832b69582adb50eacc2a9a32a9f403cb6a8c8c76687648e90d1a032d16af92"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "9e89e79e1e7cde392051631f788b3f6f4d7cd2f1"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[NetCDF.download]]
    sha256 = "44845313ecffa75bf59802ba8106541124b1e1ea7122dc0404040f2c54c90be8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-linux-musl-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "837fbd05d2110a98964efcb0c553e06ba8ef92f4"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[NetCDF.download]]
    sha256 = "c415e218e6cfddbbf68c2ca769d8aeed5231867d631393b9bd87d9518773fa47"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "88895ecc8bca26dd441123af8a9ee139537ca8c2"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "8a27360061860264e33d88a35bf1fc26d3e1034da49126852db8c324211f743b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "fd036099befe0ef0ce23121665fab728ad0d9900"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "3d655d62643f905463c649ff02711a37cc3eceb0a43d81fe6a6a05b77f133978"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "4932379760c263161349e7bec9b83579a74a3112"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "c86d070cb5c1e9928486fa3d0703b3cd4b96bc279a98b9523394eac1bf66fcb4"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "980a50b346ff20e4b0474a9d23dbd9056979d498"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[NetCDF.download]]
    sha256 = "8a0573833decb59b4e6004ec672a5086e48f516f1b3eac9df32818522fa32eea"
    url = "https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/download/NetCDF-v400.902.300+0/NetCDF.v400.902.300.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
